### ISSUE TITLE
Support for JS-based config in frontend-platform

### ISSUE THREAD

**Issue by davidjoy** [openedx/wg-frontend#11]
https://github.com/edx/frontend-platform needs to be updated to allow for JS-based configuration.

This should look something like:

- [ ] Packaging the existing `process.env` configuration into a `ProcessEnvConfigService` and putting an `interface.js` abstraction layer around it.
- [ ] Create an `ImportConfigService` (or a better name) which imports configuration from `'env.config'`, as expected in frontend-build.  
- [ ] Determine the right rollout strategy which enables backwards compatibility with the existing process.env-based configuration, while allowing MFEs to opt into the JS-based configuration.

```[tasklist]
#### PRs
- [ ] https://github.com/openedx/frontend-platform/pull/474
```

**Comment by ghassanmas** [comment]
@davidjoy is this open for the community to own? or is it something edx is already working on internally? 
I ask because I am interested in working on it (given also this has been brought up in the last FEWG #49)
