### ISSUE TITLE
Plug in to enable test-driving Content Libraries v2 functionality

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/wg-frontend#154]
The primary piece of functionality in Content Libraries V2 is to enable authors to create component xblocks in the Library and then add those components to one or multiple courses. Additional info is [here](https://github.com/openedx/platform-roadmap/issues/220).

This functionality is contingent on the Library Authoring MFE, which is not ready for a Named Release yet. As a workaround, OpenCraft created an [unofficial Tutor plugin for the Library Authoring MFE](https://github.com/openedx/frontend-app-library-authoring/tree/master/tutor-contrib-library-authoring-mfe), but:

1. It only works in development mode (i.e, `tutor dev`)
2. It has not been updated for Olive (i.e., Tutor 15.0.0)

**Acceptance Criteria**

A set of updated plugins that will enable interested providers to automatically configure blockstore and start running the Library Authoring MFE frontend in "alpha", so that they can test-drive the new Content Libraries v2 functionality.

OpenCraft created [a demo](https://drive.google.com/file/d/14IXfgvmizMQUItRpHolmaUXBIf7jCBvM/view) of how the current Library Authoring plugin works and what users will be able to do once it's running - namely:

- Interact with Content Libraries V2
- Add new text, problems and video components to content libraries
- Pull those components from content libraries into their courses in Studio via the "Library Sourced" button (requires configuration in Advanced Settings, "library_sourced")

The expectation is that a new or updated Library Authoring Tutor plugin, in conjunction with a new Blockstore plugin, will achieve parity in terms of enabling users to test the functionality, as described above.

In addition:

#### Blockstore plugin

- [ ] Works as well with `tutor local launch` as with the legacy devstack
- [ ] Works with block storage, and in particular, with the Tutor minio plugin
- [ ] Works with S3
- [ ] Works with Kubernetes

#### Library Authoring plugin

- [ ] Works with the Blockstore plugin
- [ ] Works with `tutor local`, and not just `tutor dev`
- [ ] `tutor plugins enable library_authoring_mfe` turns the MFE on automatically - no further need for feature flag or waffle flag manual manipulation
- [ ] The new editors should be enabled by default (depends on the course-authoring MFE)

### Other considerations

Content Libraries V2 is not a finished product. The new editors are only partially complete. Thus, the expectation is not that we are presenting users with new, shiny functionality. Rather, we want to give power-users the ability to play around with the new functionality in an alpha environment, to provide early feedback, etc.

**Open questions**

* What happens if you enable the Library Authoring MFE plugin, but not the Blockstore one?
  * Maybe some specific error message in the MFE's UI when Blockstore is not there

**Comment by brian-smith-tcril** [comment]
i'm on it!

**Comment by arbrandes** [comment]
Forgot to close this one!  (The plugin lives in https://github.com/openedx/openedx-tutor-plugins/tree/main/plugins/tutor-contrib-library-authoring-mfe).
