### ISSUE TITLE
Documentation for overriding the header and footer

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-frontend#164]
### Background

A community member recently asked how they could make changes to the MFE headers and footers. I could not find any existing documentation to point them to. The best I found was [this forum thread](https://discuss.openedx.org/t/mfe-header-override/5125/14).

### Acceptance Criteria

Add documentation for header/footer overrides to https://github.com/openedx/docs.openedx.org.

Suggested parent page: [Site Operators > How Tos](https://docs.openedx.org/en/latest/site_ops/how-tos/index.html)

**Comment by davidjoy** [comment]
Heyo - this looks like a duplicate of this issue: https://github.com/openedx/docs.openedx.org/issues/272

**Comment by kdmccormick** [comment]
A dupe it is indeed!
