### ISSUE TITLE
Notify upstream owners of new-relic-source-map-webpack-plugin

### ISSUE THREAD

**Issue by davidjoy** [openedx/wg-frontend#23]
Decide if we want to inform the upstream owners of new-relic-source-map-webpack-plugin that we're maintaining a fork that works with webpack 5.

**Comment by adamstankiewicz** [comment]
@twhid We needed the new-relic-source-map-webpack-plugin to be compatible with Webpack 5 but that plugin hasn't been updated recently and is currently archived. I forked the repo and made the necessary fixes to make it compatible with Webpack 5 here: https://github.com/edx/new-relic-source-map-webpack-plugin

We figured it'd be worth letting you know (as the initial commiter of `new-relic-source-map-webpack-plugin`) as it may be worthwhile to link to our Webpack 5 compatible fork from the README for any other teams who need this plugin to work with Webpack 5.

For example, maybe something along the lines of [this](https://github.com/dollarshaveclub/es-check):
![image](https://user-images.githubusercontent.com/2828721/140005323-9a88f8bc-6d6e-44d3-bf4f-ad0bdf320952.png)
