### ISSUE TITLE
Resolve npm dependency issues in edx-platform

### ISSUE THREAD

**Issue by ghassanmas** [openedx/wg-frontend#26]
The [edx-platform](https://github.com/edx/edx-platform)  has conflict in package dependency. This can help to resolve since various process or scripts starts by running `npm install` in the root of `edx-platform` which might take time even if `node_modules` have been already installed. since `npm install` runs preinstall cycle anyway [REF](https://docs.npmjs.com/cli/v6/using-npm/scripts#npm-install)

This issue might not too related to FEWG. however, it might be helpful to post here since it's related to FEWG  type of expertise. 

### 1- `edx/edx-proctoring `

MFE-Platform is `edx/edx-proctoring@1.5.0` while `edx-proctoring-proctortrack` is using `edx/edx-proctoring@3.8.0` [REF|https://github.com/anupdhabarde/edx-proctoring-proctortrack/blob/d717f3b7e1d5aec6290d7dd08646cba8c6af3499/package.json#L26]. 
Note: I am not sure about how `edx-proctoring-proctortrack` is intended to be installed, the link source returns the master branch [here](https://github.com/edx/edx-platform/blob/418fd7f4b17177f0858fea5d932b7a03ee2c40bc/package.json#L29)

### 2- `selenium-webdriver`
There multiple pacakges in dev depedency that uses the `selenium-webdriver`, however they conflict with each other, for example, `karma-selenium-webdriver-launcher` is using `selenium-webdriver@2.44.0` [REF](https://github.com/PixnBits/karma-selenium-webdriver-launcher/blob/8b9552e90d8311b1b98cff027ca0d47c2c58b46b/package.json?_pjax=%23repo-content-pjax-container#L24) however the platform it self is using `selenium-webdriver@3.4.0`  [REF](https://github.com/edx/edx-platform/blob/418fd7f4b17177f0858fea5d932b7a03ee2c40bc/package.json#L102)

## Other Relevant Links

* https://github.com/openedx/wg-frontend/issues/105#issuecomment-1693469425
* https://github.com/edx/edx-arch-experiments/issues/262#issuecomment-1845193450
* Cleanup that got reverted that might need to be put back on master: https://github.com/openedx/edx-platform/pull/33542
* https://github.com/openedx/edx-platform/issues/31937#issuecomment-1560741830

**Comment by mamankhan99** [comment]
karma-selenium-webdriver-launcher@0.0.4 is the latest version that is using selenium-webdriver@2.44.0 so an update is not possible here. I believe it isn't breaking anything at the moment and we can eventually exclude these packages from the project when we will break it down into more MFEs till then we can keep it.

**Comment by arbrandes** [comment]
@abdullahwaheed, @ishahroz: is this related to the Karma vs Jest conversation we had today?  Is there another issue that tracks that?

**Comment by abdullahwaheed** [comment]
yes this issue is covered in #105 as well

**Comment by kdmccormick** [comment]
Some vague questions:

1. why is something installing selenium?
2. why is edx-proctoring or edx-proctoring-proctortrack installing into edx-platform as a node package, given that (I believe) it's been fully replatformed into an MFE?

**Comment by feanil** [comment]
The proctoring issue has been resolved here: https://github.com/openedx/edx-platform/pull/34874

**Comment by feanil** [comment]
`npm install` now works cleanly so I'm gonna close this for now.
