### ISSUE TITLE
Upgrade eslint to v8.x

### ISSUE THREAD

**Issue by davidjoy** [openedx/wg-frontend#42]
We're currently using eslint v6.x.  We'd like to upgrade this to the latest stable release v8.x.  

We should be able to do this without creating any new linting errors, hopefully.  

Also, it's worth noting that automated updates in https://github.com/edx/eslint-config updated our version of eslint there to 7.x.  These dependencies are only used in development of the eslint-config, as it declares them as peer dependencies.  https://github.com/edx/frontend-build defines the actual eslint dependencies we use, which use v6.x.  So, despite our config being on v7, everything else is still on v6.x and (luckily) nothing has broken.  We should straighten out this situation when doing this upgrade.

#### Base

- [x] https://github.com/openedx/frontend-build/pull/252
- [x] https://github.com/openedx/frontend-platform/pull/354
- [x] https://github.com/openedx/paragon/pull/1421
- [x] https://github.com/openedx/frontend-template-application/pull/472

#### Components

- [x] https://github.com/openedx/frontend-component-header/pull/249
- [x] https://github.com/edx/frontend-component-header-edx/pull/277
- [x] https://github.com/openedx/frontend-component-footer/pull/228
- [x] https://github.com/edx/frontend-component-footer-edx/pull/196
- [x] https://github.com/openedx/frontend-component-cookie-policy-banner/pull/403

#### MFEs

- [ ] https://github.com/openedx/frontend-app-gradebook/pull/254
- [x] https://github.com/openedx/frontend-app-publisher/pull/757
- [x] https://github.com/openedx/frontend-app-admin-portal/pull/901
- [x] https://github.com/openedx/frontend-app-profile/pull/589
- [ ] https://github.com/openedx/frontend-app-ecommerce/pull/204
- [x] https://github.com/openedx/frontend-app-account/pull/613
- [ ] https://github.com/openedx/frontend-app-course-authoring/pull/322
- [x] https://github.com/openedx/frontend-app-library-authoring/pull/51
- [x] https://github.com/openedx/frontend-app-learner-record/pull/72
- [ ] https://github.com/edx/frontend-app-communications/pull/66
- [ ] https://github.com/openedx/frontend-app-learning/pull/962
- [ ] https://github.com/openedx/frontend-app-payment/pull/620
- [x] https://github.com/openedx/frontend-app-learner-portal-programs/pull/249
- [x] https://github.com/openedx/frontend-app-profile/pull/654

#### Enterprise

- [ ] https://github.com/openedx/frontend-enterprise/pull/270
- [x] https://github.com/openedx/frontend-app-enterprise-public-catalog/pull/244
- [ ] https://github.com/openedx/frontend-app-enterprise-public-catalog/pull/265
- [ ] https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/593

**Comment by BilalQamar95** [comment]
@arbrandes Yes, these are waiting for reviews/merges

**Comment by BilalQamar95** [comment]
> @BilalQamar95, are we done here?

Yes, seems concluded.
