### ISSUE TITLE
use 'npm ci' instead of 'npm install' for frontend builds

### ISSUE THREAD

**Issue by dianekaplan** [openedx/wg-frontend#48]
The gocd generated pipelines use 'npm install' rather than 'npm ci', thanks to tubular/scripts/frontend_build.py and frontend_utils- see here: https://github.com/edx/tubular/blob/master/tubular/scripts/frontend_utils.py#L59

'npm ci' is preferable, as it is more strict about reproducing the package versions set in the package-lock.json (whereas 'npm install' blows it away and can use different versions). 

Phil Shiu and David Joy have discussed that this should be corrected to npm ci. Logging here for tracking/info, since it affects many MFEs.

**Comment by adamstankiewicz** [comment]
It may be worth prioritizing the `npm install` -> `npm ci` change in tubular at [the linked shared above](https://github.com/openedx/tubular/blob/2fcfc4edb8cf890be026c3800cf998804891031f/tubular/scripts/frontend_utils.py#L59) over making the change in CI for each individual MFE (though both are important).

Rationale being if we only change the CI in individual MFEs to run `npm ci` instead, when a PR merges to `master` in that MFE and runs through the GoCD build and deploy pipeline, it'll still run `npm install` before releasing to stage/prod, potentially/theoretically pulling in later `node_modules` than explicitly defined in the package-lock.json file.

I think it may make sense to tackle tubular first and then the individual MFEs.

**Comment by abdullahwaheed** [comment]
we are [overriding(e.g.)](https://github.com/edx/edx-internal/blob/098edaeaec9b63497c5947f91886b27a7bf2ada5/frontends/frontend-app-ecommerce/prod_config.yml#L14) header and footer packages with NPM aliases using edx-internal configuration. Since `package-lock.json` and `package.json` will not match with this override, when we'll use `npm ci`, it would crash!

Ref: https://stackoverflow.com/questions/52499617/what-is-the-difference-between-npm-install-and-npm-ci#answer-53325242

**Comment by adamstankiewicz** [comment]
@abdullahwaheed I believe only the `npm install` for the repo's base dependencies should need to be flipped to `npm ci` ([source](https://github.com/openedx/tubular/blob/de9b83060fe1820ddbdaa2bdfdc20f3255e1141c/tubular/scripts/frontend_utils.py#L59)), whereas the installation of the NPM alias override(s) would stick to using `npm install`.

The latter install for NPM alias overrides does not read from package.json or package-lock.json; it just installs over whatever default package was installed in package-lock.json for the repo.

Replicating the build process in GoCD locally works without error, e.g.:

```shell
npm ci
npm install @edx/brand@npm:@edx/brand-edx.org@2
```

Technically, that latter install will modify the package-lock.json file, but those changes are local to GoCD during the build + deploy process and never committed back to the repo. We could prevent the [latter `npm install` for the aliases](https://github.com/openedx/tubular/blob/de9b83060fe1820ddbdaa2bdfdc20f3255e1141c/tubular/scripts/frontend_utils.py#L79) from mutating package-lock.json by including the `--no-save` argument.

**Comment by abdullahwaheed** [comment]
@adamstankiewicz thank you for clarification. You are right, i have missed the part where we are using package installation and alias installation separately.

**Comment by abdullahwaheed** [comment]
Its [PR](https://github.com/openedx/tubular/pull/608) is ready for review

**Comment by arbrandes** [comment]
Looks like tubular is on its way out from the openedx org.  Plus, the PR is merged.  Closing.
