### ISSUE TITLE
Migrate from Coveralls to Codecov

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/wg-frontend#9]
Most of our frontend related repositories are now using Codecov for coverage diffs and reporting. However, there are still some repositories still using Coveralls. We should replace all uses of Coveralls with Codecov.

- [ ] Identify all the places Coveralls is still in use.
- [ ] Swap out Coveralls for Codecov in these identified places.

**Comment by Mashal-m** [comment]
> It seems to me that the last one was the studio-frontend one, and I just merged it. Can we confirm we're done here?

Yes, we are done.
